name: Disney Bot
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ここで改めて書き込みを宣言
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # これを追加
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests pandas
      - name: Run collector
        run: python collector.py
      - name: Save data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wait_times_history.csv
          git commit -m "update wait times" || exit 0
          git push origin main
